### ISSUE TITLE
Fix Slide Cells

### ISSUE THREAD

**Issue by iamzoltan** [neuromatch/climate-course-content#60]
It looks like we are not properly labeling the slide cells. As of now, there seems to be no huge issue, since we are including most of the code that is automatically replaced. Ideally we simplify the code in the books and label the cells appropriately.

@nsea-log

**Comment by iamzoltan** [comment]
@nsea-log was this addressed?

**Comment by nsea-log** [comment]
@iamzoltan yes, the material of week 2 is updated in this regard (release-v0.2.1). Week 1 still needs an update of the slide cells.
