### ISSUE TITLE
DATASETS import error W1D1 T6&3

### ISSUE THREAD

**Issue by ocgabs** [neuromatch/climate-course-content#69]
On Tutorials 3 and 6 of week 1 day 1, I am getting an error when running the import cell:
# imports
import xarray as xr
from pythia_datasets import DATASETS
import matplotlib.pyplot as plt

No module named 'pythia_datasets'

**Comment by nsea-log** [comment]
Hi @ocgabs, would you mind adding your environment? Are you using our JupyterHub instance, Google colab or Kaggle, or do you even run it locally? Thank you, Paul

**Comment by ocgabs** [comment]
Yes, sorry, I was using Jupyter Hub, does this path looks about right for this year? https://climatematch.2i2c.cloud/user/ocgabs/lab/workspaces/auto-H/tree/climate-course-content/tutorials/W1D1_ClimateSystemOverview/W1D1_Tutorial6.ipynb

**Comment by nsea-log** [comment]
Hi @ocgabs, please restart your JupyterHub and retry running T3 & T6, we think we found the issue :) Happy to get another round of feedback if not.

**Comment by ocgabs** [comment]
It works now, thanks... I wonder what was the problem and how was it fixed... feel free to close this issue now
